name: windows 64bit

on: [push, pull_request]

env:
  PYTHON_VER: '3.8.1'
  PYTHON_VER_DIRNAME: 'python38'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VER }}
          architecture: 'x64'

      - name: Download dependencies
        run: |
          wget https://download.qt.io/official_releases/jom/jom.zip -OutFile jom.zip
          wget https://github.com/thp/pyotherside/archive/1.5.9.zip -OutFile pyotherside-1.5.9.zip
          wget https://developers.yubico.com/yubikey-personalization/Releases/ykpers-1.20.0-win64.zip -OutFile ykpers-1.20.0-win64.zip
          wget https://developers.yubico.com/yubikey-personalization/Releases/ykpers-1.20.0-win64.zip.sig -OutFile ykpers-1.20.0-win64.zip.sig
          wget https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z -OutFile libusb-1.0.22.7z
          wget https://www.python.org/ftp/python/$env:PYTHON_VER/python-$env:PYTHON_VER-embed-amd64.zip -OutFile python-$env:PYTHON_VER-embed-amd64.zip
        shell: powershell

      - name: Fetch GPG keys
        run: gpg --no-default-keyring --keyring yubico --keyserver hkps://keys.openpgp.org --recv-keys 0A3B0262BCA1705307D5FF06BCA00FD4B2168C0A

      - name: Verify checksums of downloaded files
        run: |
          sha256sum -c ./.github/workflows/windows-x64-libs.sha256sum
          gpg --no-default-keyring --keyring yubico --verify ykpers-1.20.0-win64.zip.sig ykpers-1.20.0-win64.zip

      - name: Install swig
        run: choco install swig

      - name: Install Qt and Jom
        run: |
          pip install aqtinstall==0.6
          python -m aqt install 5.13.1 windows desktop win64_msvc2017_64
          7z x jom.zip
        shell: powershell

      - name: Download and prepare pyotherside
        run: |
          7z x pyotherside-1.5.9.zip
          cd pyotherside-1.5.9
          (Get-Content .\src\qmldir).replace('pyothersideplugin', 'pyothersideplugin1') | Set-Content .\src\qmldir
          Clear-Content python.pri
          Add-Content python.pri "PYTHON_CONFIG = python3-config`nQMAKE_LIBS += -LC:\hostedtoolcache\windows\Python\$env:PYTHON_VER\x64\libs -l$env:PYTHON_VER_DIRNAME`nQMAKE_CXXFLAGS += -IC:\hostedtoolcache\windows\Python\$env:PYTHON_VER\x64\include`n"
        shell: powershell

      - name: Build and install pyotherside
        shell: cmd
        run: |
          set PATH=D:\a\yubikey-manager-qt\yubikey-manager-qt\5.13.1\msvc2017_64\bin;D:\a\yubikey-manager-qt\yubikey-manager-qt;%PATH%
          call C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x64
          cd pyotherside-1.5.9
          qmake
          jom
          jom install

      - name: Build app
        shell: cmd
        run: |
          set PATH=D:\a\yubikey-manager-qt\yubikey-manager-qt\5.13.1\msvc2017_64\bin;D:\a\yubikey-manager-qt\yubikey-manager-qt;%PATH%
          call C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x64
          qmake
          jom

      - name: Run windeployqt
        shell: cmd
        run: |
          set PATH=D:\a\yubikey-manager-qt\yubikey-manager-qt\5.13.1\msvc2017_64\bin;D:\a\yubikey-manager-qt\yubikey-manager-qt;%PATH%
          call C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x64
          windeployqt .\ykman-gui\release\ykman-gui.exe --qmldir=.\ykman-gui\qml --no-translations --angle --release

      - name: Copy over files and create .zip archive
        run: |
          Copy-Item .\ykman-gui\pymodules .\ykman-gui\release -recurse
          Get-ChildItem -File -Include *.pyc -Recurse | Remove-Item -Force
          Get-ChildItem -Include __pycache__ -Recurse | Remove-Item -Force
          Get-ChildItem -Include *.cpp -Recurse | Remove-Item -Force
          Get-ChildItem -Include *.obj -Recurse | Remove-Item -Force
          Copy-Item .\ykman-cli\release\ykman.exe .\ykman-gui\release

          7z x ykpers-1.20.0-win64.zip
          Copy-Item .\bin\*.dll .\ykman-gui\release\pymodules\ykman\native -Force

          7z x libusb-1.0.22.7z
          Copy-Item .\MS64\dll\*.dll .\ykman-gui\release\pymodules\ykman\native -Force

          cd .\ykman-gui\release
          7z x ..\..\python-$env:PYTHON_VER-embed-amd64.zip
          cd ../..

          $arr = $env:GITHUB_REF -split '/'
          $branch = $arr[2]
          7z a yubikey-manager-qt-$branch-win64.zip .\ykman-gui\release

          mkdir deploy
          cp yubikey-manager-qt-$branch-win64.zip deploy
        shell: powershell

      - name: Install Visual Studio C++ 2019 Redistributable MSMs
        shell: cmd
        run: |
          choco install visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Component.VC.Redist.MSM"
      
      - name: Create an unsigned .msi installer package
        run: |
          cd .\ykman-gui\
          $env:PATH += ";$env:WIX\bin"
          $env:SRCDIR = ".\release\"
          $env:MERGEDPATH = Get-ChildItem "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\*\MergeModules\Microsoft_VC142_CRT_x64.msm"
          heat dir .\release -out fragment.wxs -gg -scom -srd -sfrag -dr INSTALLDIR -cg ApplicationFiles -var env.SRCDIR
          candle .\fragment.wxs ..\resources\win\yubikey-manager.wxs -arch x64
          light fragment.wixobj yubikey-manager.wixobj -ext WixUIExtension -ext WixUtilExtension -o yubikey-manager.msi
          cp yubikey-manager.msi ../deploy

      - name: Run installer
        shell: cmd
        run: |
          cd .\ykman-gui\
          msiexec /i yubikey-manager.msi /quiet /l .\log.txt
          cat .\log.txt
          
      - name: Rename installer
        shell: powershell
        run: |
          $arr = $env:GITHUB_REF -split '/'
          $branch = $arr[2]
          mv .\deploy\yubikey-manager.msi .\deploy\yubikey-manager-$branch-win64.msi

      - name: Run GUI
        shell: bash
        run: |
          ./ykman-gui/release/ykman-gui --version
          ./ykman-gui/release/ykman-gui --help

      - name: Run CLI
        shell: bash
        run: |
          ./ykman-gui/release/ykman --version
          [[ -z "$(./ykman-gui/release/ykman --version | grep -E "not found|missing")" ]]

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubikey-manager-qt-win64
          path: deploy
